Update build-turnip.yml

diff --git a/.github/workflows/build-turnip.yml b/.github/workflows/build-turnip.yml
--- a/.github/workflows/build-turnip.yml
+++ b/.github/workflows/build-turnip.yml
@@ -82,21 +82,30 @@ jobs:
 
           echo "ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/28.2.13676358" \
             >> "$GITHUB_ENV"
-
+   
       - name: Clone Mesa
-        shell: bash
+        env:
+          MESA_REF: mesa-26.1.4
         run: |
-          set -euxo pipefail
+          set -e
 
-          git clone \
-            --filter=blob:none \
-            https://gitlab.freedesktop.org/mesa/mesa.git \
-            mesa
+          git clone https://gitlab.freedesktop.org/mesa/mesa.git mesa
 
           cd mesa
-          git checkout "${{ inputs.mesa_ref }}"
-          git rev-parse HEAD | tee ../mesa-commit.txt
 
+          echo "Mesa seleccionada: ${MESA_REF}"
+
+          if [ -z "${MESA_REF}" ]; then
+            echo "ERROR: MESA_REF está vacía"
+            exit 1
+          fi
+
+          git checkout "${MESA_REF}"
+
+          echo "Commit de Mesa:"
+          git rev-parse HEAD 
+      
+    
       - name: Apply optional patches
         shell: bash
         run: |
@@ -127,9 +136,9 @@ jobs:
       - name: Package Eclipse R3
         shell: bash
         env:
-          BUILD_NAME: "${{ inputs.build_name }}"
-          MESA_REF: "${{ inputs.mesa_ref }}"
-          RELEASE_NAME: "Turnip-MV-Eclipse-R3"
+            BUILD_NAME: "Turnip MV Eclipse R3"
+            MESA_REF: "mesa-26.1.4"
+            RELEASE_NAME: "Turnip-MV-Eclipse-R3"  
         run: |
           set -euxo pipefail
           chmod +x scripts/package-driver.sh
